Parallelize ssh tests (#570)
Note: current includes changes from #557 as well.

Closes #563 

Removes reliance on `--dist=loadgroup` and
`@pytest.mark.xdist_group(...)` to run SSH tests in a single worker by
implementing a portable file-lock based serialization method for test
service setup/teardown and separating out services that might interact
between tests.

In my local testing, this seems to solve both the "successful but
non-reported tests" issue, limited discoverability of tests in vscode
upon failure, and lack of parallel execution in all dev environments
(Windows, WSL Devcontainer, Linux).

On occassion in Windows I have seen the following error, but it is after
tests have passed, so seems to be part of pytest cleanup:

```
...
[gw4] [100%] PASSED mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_host_service.py::test_ssh_service_reboot

=================================================================================================================================== warnings summary ==================================================================================================================================== 
mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_fileshare.py::test_ssh_fileshare_upload_file_dne
  C:\Users\bpkroth\.conda\envs\mlos\lib\site-packages\_pytest\threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-9 (_run_event_loop)

  Traceback (most recent call last):
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\windows_events.py", line 494, in finish_recv
      return ov.getresult()
  OSError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\windows_events.py", line 826, in _poll
      value = callback(transferred, key, ov)
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\windows_events.py", line 498, in finish_recv
      raise ConnectionResetError(*exc.args)
  ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "C:\Users\bpkroth\src\MLOS\mlos_bench\mlos_bench\event_loop_context.py", line 48, in _run_event_loop
      self._event_loop.run_forever()
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\windows_events.py", line 321, in run_forever
      super().run_forever()
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\base_events.py", line 603, in run_forever
      self._run_once()
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\base_events.py", line 1871, in _run_once
      event_list = self._selector.select(timeout)
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\windows_events.py", line 444, in select
      self._poll(timeout)
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\windows_events.py", line 828, in _poll
      f.set_exception(e)
    File "C:\Users\bpkroth\.conda\envs\mlos\lib\asyncio\windows_events.py", line 88, in set_exception
      super().set_exception(exception)
  asyncio.exceptions.InvalidStateError: invalid state

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```

---------

Co-authored-by: Sergiy Matusevych <sergiym@microsoft.com>
Co-authored-by: Sergiy Matusevych <sergiy.matusevych@gmail.com>