Workaround an issue introduced by recent versions of sphinx
With sphinx 3.4.0-3.4.2 (released in late December 2020), sphinx generates
asserts by the Point module due to invalid keys (e.g. __sphinx_mock__) in the Point.

Exception occurred:
  File "/src/MLOS/source/Mlos.Python/mlos/Spaces/Point.py", line 75, in __getitem__
    raise KeyError(f"This Point does not have a value along dimension: {dimension_name}")
KeyError: 'This Point does not have a value along dimension: __sphinx_mock__'